import { ReactNode } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Provider } from 'react-redux'
import { store } from "@/store";
import { ErrorBoundary } from "react-error-boundary";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: { children: [ReactNode] | ReactNode}) {

  return (
    <ErrorBoundary fallback={<div>Error Handeling Goes Here</div>}>
      <Head>
        <title>Poke List App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Provider store={store}>
          {children}
        </Provider>
       
      </main>
    </ErrorBoundary>
  );
}
